apiVersion: apps/v1
kind: Deployment
metadata:
  name: wxapp-server-deployment
spec:
  selector:
    matchLabels:
      app: wxapp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: wxapp-server
        version: __LABEL_VERSION__
    spec:
      containers:
        - name: wxapp-server
          image: myz/wxapp-server:1.0
          ports:
            - containerPort: 5050
              name: wxapp-server
