dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181/dubbo
  protocol:
    name: tri
    port: 5050

database:
  common:
    validationQuery: SELECT 1

  dbuser:
    username: wxapp
    password: wxapp1234
    url: jdbc:mariadb://10.8.0.1:31306/wxapp
    driverClassName: org.mariadb.jdbc.Driver
    initialSize: 0
    maxTotal: 4
    maxIdle: 4
    minIdle: 0
