// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.myz.wxapp.api.task;

public interface CancelTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.CancelTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int64 taskId = 2;</code>
   * @return The taskId.
   */
  long getTaskId();
}
