// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.myz.wxapp.api.task;

/**
 * Protobuf type {@code task.CreateTaskRequest}
 */
public final class CreateTaskRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:task.CreateTaskRequest)
    CreateTaskRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateTaskRequest.newBuilder() to construct.
  private CreateTaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateTaskRequest() {
    name_ = "";
    description_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateTaskRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.myz.wxapp.api.task.TaskProto.internal_static_task_CreateTaskRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.myz.wxapp.api.task.TaskProto.internal_static_task_CreateTaskRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.myz.wxapp.api.task.CreateTaskRequest.class, com.myz.wxapp.api.task.CreateTaskRequest.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_ = 0L;
  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object description_ = "";
  /**
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TASKTYPE_FIELD_NUMBER = 4;
  private int taskType_ = 0;
  /**
   * <code>int32 taskType = 4;</code>
   * @return The taskType.
   */
  @java.lang.Override
  public int getTaskType() {
    return taskType_;
  }

  public static final int EXECTYPE_FIELD_NUMBER = 5;
  private int execType_ = 0;
  /**
   * <code>int32 execType = 5;</code>
   * @return The execType.
   */
  @java.lang.Override
  public int getExecType() {
    return execType_;
  }

  public static final int PERIODTYPE_FIELD_NUMBER = 6;
  private int periodType_ = 0;
  /**
   * <code>int32 periodType = 6;</code>
   * @return The periodType.
   */
  @java.lang.Override
  public int getPeriodType() {
    return periodType_;
  }

  public static final int FIRETIME_FIELD_NUMBER = 7;
  private long fireTime_ = 0L;
  /**
   * <code>int64 fireTime = 7;</code>
   * @return The fireTime.
   */
  @java.lang.Override
  public long getFireTime() {
    return fireTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, description_);
    }
    if (taskType_ != 0) {
      output.writeInt32(4, taskType_);
    }
    if (execType_ != 0) {
      output.writeInt32(5, execType_);
    }
    if (periodType_ != 0) {
      output.writeInt32(6, periodType_);
    }
    if (fireTime_ != 0L) {
      output.writeInt64(7, fireTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, description_);
    }
    if (taskType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, taskType_);
    }
    if (execType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, execType_);
    }
    if (periodType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, periodType_);
    }
    if (fireTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, fireTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.myz.wxapp.api.task.CreateTaskRequest)) {
      return super.equals(obj);
    }
    com.myz.wxapp.api.task.CreateTaskRequest other = (com.myz.wxapp.api.task.CreateTaskRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getDescription()
        .equals(other.getDescription())) return false;
    if (getTaskType()
        != other.getTaskType()) return false;
    if (getExecType()
        != other.getExecType()) return false;
    if (getPeriodType()
        != other.getPeriodType()) return false;
    if (getFireTime()
        != other.getFireTime()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + TASKTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTaskType();
    hash = (37 * hash) + EXECTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getExecType();
    hash = (37 * hash) + PERIODTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getPeriodType();
    hash = (37 * hash) + FIRETIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFireTime());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myz.wxapp.api.task.CreateTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.myz.wxapp.api.task.CreateTaskRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code task.CreateTaskRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:task.CreateTaskRequest)
      com.myz.wxapp.api.task.CreateTaskRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myz.wxapp.api.task.TaskProto.internal_static_task_CreateTaskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myz.wxapp.api.task.TaskProto.internal_static_task_CreateTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.myz.wxapp.api.task.CreateTaskRequest.class, com.myz.wxapp.api.task.CreateTaskRequest.Builder.class);
    }

    // Construct using com.myz.wxapp.api.task.CreateTaskRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      userId_ = 0L;
      name_ = "";
      description_ = "";
      taskType_ = 0;
      execType_ = 0;
      periodType_ = 0;
      fireTime_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.myz.wxapp.api.task.TaskProto.internal_static_task_CreateTaskRequest_descriptor;
    }

    @java.lang.Override
    public com.myz.wxapp.api.task.CreateTaskRequest getDefaultInstanceForType() {
      return com.myz.wxapp.api.task.CreateTaskRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.myz.wxapp.api.task.CreateTaskRequest build() {
      com.myz.wxapp.api.task.CreateTaskRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.myz.wxapp.api.task.CreateTaskRequest buildPartial() {
      com.myz.wxapp.api.task.CreateTaskRequest result = new com.myz.wxapp.api.task.CreateTaskRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.myz.wxapp.api.task.CreateTaskRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.userId_ = userId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.description_ = description_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.taskType_ = taskType_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.execType_ = execType_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.periodType_ = periodType_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.fireTime_ = fireTime_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.myz.wxapp.api.task.CreateTaskRequest) {
        return mergeFrom((com.myz.wxapp.api.task.CreateTaskRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.myz.wxapp.api.task.CreateTaskRequest other) {
      if (other == com.myz.wxapp.api.task.CreateTaskRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getTaskType() != 0) {
        setTaskType(other.getTaskType());
      }
      if (other.getExecType() != 0) {
        setExecType(other.getExecType());
      }
      if (other.getPeriodType() != 0) {
        setPeriodType(other.getPeriodType());
      }
      if (other.getFireTime() != 0L) {
        setFireTime(other.getFireTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              description_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              taskType_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              execType_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              periodType_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              fireTime_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {

      userId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      description_ = getDefaultInstance().getDescription();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      description_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int taskType_ ;
    /**
     * <code>int32 taskType = 4;</code>
     * @return The taskType.
     */
    @java.lang.Override
    public int getTaskType() {
      return taskType_;
    }
    /**
     * <code>int32 taskType = 4;</code>
     * @param value The taskType to set.
     * @return This builder for chaining.
     */
    public Builder setTaskType(int value) {

      taskType_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 taskType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTaskType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      taskType_ = 0;
      onChanged();
      return this;
    }

    private int execType_ ;
    /**
     * <code>int32 execType = 5;</code>
     * @return The execType.
     */
    @java.lang.Override
    public int getExecType() {
      return execType_;
    }
    /**
     * <code>int32 execType = 5;</code>
     * @param value The execType to set.
     * @return This builder for chaining.
     */
    public Builder setExecType(int value) {

      execType_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 execType = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExecType() {
      bitField0_ = (bitField0_ & ~0x00000010);
      execType_ = 0;
      onChanged();
      return this;
    }

    private int periodType_ ;
    /**
     * <code>int32 periodType = 6;</code>
     * @return The periodType.
     */
    @java.lang.Override
    public int getPeriodType() {
      return periodType_;
    }
    /**
     * <code>int32 periodType = 6;</code>
     * @param value The periodType to set.
     * @return This builder for chaining.
     */
    public Builder setPeriodType(int value) {

      periodType_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 periodType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPeriodType() {
      bitField0_ = (bitField0_ & ~0x00000020);
      periodType_ = 0;
      onChanged();
      return this;
    }

    private long fireTime_ ;
    /**
     * <code>int64 fireTime = 7;</code>
     * @return The fireTime.
     */
    @java.lang.Override
    public long getFireTime() {
      return fireTime_;
    }
    /**
     * <code>int64 fireTime = 7;</code>
     * @param value The fireTime to set.
     * @return This builder for chaining.
     */
    public Builder setFireTime(long value) {

      fireTime_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 fireTime = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearFireTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      fireTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:task.CreateTaskRequest)
  }

  // @@protoc_insertion_point(class_scope:task.CreateTaskRequest)
  private static final com.myz.wxapp.api.task.CreateTaskRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.myz.wxapp.api.task.CreateTaskRequest();
  }

  public static com.myz.wxapp.api.task.CreateTaskRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateTaskRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateTaskRequest>() {
    @java.lang.Override
    public CreateTaskRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateTaskRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateTaskRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.myz.wxapp.api.task.CreateTaskRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

