// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.myz.wxapp.api.task;

public interface CreateTaskReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.CreateTaskReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 taskId = 1;</code>
   * @return The taskId.
   */
  long getTaskId();
}
