// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.myz.wxapp.api.task;

public interface QueryTaskResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.QueryTaskResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 length = 1;</code>
   * @return The length.
   */
  int getLength();

  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  java.util.List<com.myz.wxapp.api.task.UserTask> 
      getTasksList();
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  com.myz.wxapp.api.task.UserTask getTasks(int index);
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  int getTasksCount();
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  java.util.List<? extends com.myz.wxapp.api.task.UserTaskOrBuilder> 
      getTasksOrBuilderList();
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  com.myz.wxapp.api.task.UserTaskOrBuilder getTasksOrBuilder(
      int index);
}
