// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.myz.wxapp.api.task;

public interface QueryTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.QueryTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();
}
