// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.myz.wxapp.api.task;

/**
 * Protobuf type {@code task.QueryTaskResult}
 */
public final class QueryTaskResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:task.QueryTaskResult)
    QueryTaskResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use QueryTaskResult.newBuilder() to construct.
  private QueryTaskResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private QueryTaskResult() {
    tasks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new QueryTaskResult();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.myz.wxapp.api.task.TaskProto.internal_static_task_QueryTaskResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.myz.wxapp.api.task.TaskProto.internal_static_task_QueryTaskResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.myz.wxapp.api.task.QueryTaskResult.class, com.myz.wxapp.api.task.QueryTaskResult.Builder.class);
  }

  public static final int LENGTH_FIELD_NUMBER = 1;
  private int length_ = 0;
  /**
   * <code>int32 length = 1;</code>
   * @return The length.
   */
  @java.lang.Override
  public int getLength() {
    return length_;
  }

  public static final int TASKS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.myz.wxapp.api.task.UserTask> tasks_;
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.myz.wxapp.api.task.UserTask> getTasksList() {
    return tasks_;
  }
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.myz.wxapp.api.task.UserTaskOrBuilder> 
      getTasksOrBuilderList() {
    return tasks_;
  }
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  @java.lang.Override
  public int getTasksCount() {
    return tasks_.size();
  }
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  @java.lang.Override
  public com.myz.wxapp.api.task.UserTask getTasks(int index) {
    return tasks_.get(index);
  }
  /**
   * <code>repeated .task.UserTask tasks = 2;</code>
   */
  @java.lang.Override
  public com.myz.wxapp.api.task.UserTaskOrBuilder getTasksOrBuilder(
      int index) {
    return tasks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (length_ != 0) {
      output.writeInt32(1, length_);
    }
    for (int i = 0; i < tasks_.size(); i++) {
      output.writeMessage(2, tasks_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (length_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, length_);
    }
    for (int i = 0; i < tasks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, tasks_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.myz.wxapp.api.task.QueryTaskResult)) {
      return super.equals(obj);
    }
    com.myz.wxapp.api.task.QueryTaskResult other = (com.myz.wxapp.api.task.QueryTaskResult) obj;

    if (getLength()
        != other.getLength()) return false;
    if (!getTasksList()
        .equals(other.getTasksList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + LENGTH_FIELD_NUMBER;
    hash = (53 * hash) + getLength();
    if (getTasksCount() > 0) {
      hash = (37 * hash) + TASKS_FIELD_NUMBER;
      hash = (53 * hash) + getTasksList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.myz.wxapp.api.task.QueryTaskResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.myz.wxapp.api.task.QueryTaskResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code task.QueryTaskResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:task.QueryTaskResult)
      com.myz.wxapp.api.task.QueryTaskResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.myz.wxapp.api.task.TaskProto.internal_static_task_QueryTaskResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.myz.wxapp.api.task.TaskProto.internal_static_task_QueryTaskResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.myz.wxapp.api.task.QueryTaskResult.class, com.myz.wxapp.api.task.QueryTaskResult.Builder.class);
    }

    // Construct using com.myz.wxapp.api.task.QueryTaskResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      length_ = 0;
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
      } else {
        tasks_ = null;
        tasksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.myz.wxapp.api.task.TaskProto.internal_static_task_QueryTaskResult_descriptor;
    }

    @java.lang.Override
    public com.myz.wxapp.api.task.QueryTaskResult getDefaultInstanceForType() {
      return com.myz.wxapp.api.task.QueryTaskResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.myz.wxapp.api.task.QueryTaskResult build() {
      com.myz.wxapp.api.task.QueryTaskResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.myz.wxapp.api.task.QueryTaskResult buildPartial() {
      com.myz.wxapp.api.task.QueryTaskResult result = new com.myz.wxapp.api.task.QueryTaskResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.myz.wxapp.api.task.QueryTaskResult result) {
      if (tasksBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          tasks_ = java.util.Collections.unmodifiableList(tasks_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.tasks_ = tasks_;
      } else {
        result.tasks_ = tasksBuilder_.build();
      }
    }

    private void buildPartial0(com.myz.wxapp.api.task.QueryTaskResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.length_ = length_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.myz.wxapp.api.task.QueryTaskResult) {
        return mergeFrom((com.myz.wxapp.api.task.QueryTaskResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.myz.wxapp.api.task.QueryTaskResult other) {
      if (other == com.myz.wxapp.api.task.QueryTaskResult.getDefaultInstance()) return this;
      if (other.getLength() != 0) {
        setLength(other.getLength());
      }
      if (tasksBuilder_ == null) {
        if (!other.tasks_.isEmpty()) {
          if (tasks_.isEmpty()) {
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTasksIsMutable();
            tasks_.addAll(other.tasks_);
          }
          onChanged();
        }
      } else {
        if (!other.tasks_.isEmpty()) {
          if (tasksBuilder_.isEmpty()) {
            tasksBuilder_.dispose();
            tasksBuilder_ = null;
            tasks_ = other.tasks_;
            bitField0_ = (bitField0_ & ~0x00000002);
            tasksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTasksFieldBuilder() : null;
          } else {
            tasksBuilder_.addAllMessages(other.tasks_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              length_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.myz.wxapp.api.task.UserTask m =
                  input.readMessage(
                      com.myz.wxapp.api.task.UserTask.parser(),
                      extensionRegistry);
              if (tasksBuilder_ == null) {
                ensureTasksIsMutable();
                tasks_.add(m);
              } else {
                tasksBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int length_ ;
    /**
     * <code>int32 length = 1;</code>
     * @return The length.
     */
    @java.lang.Override
    public int getLength() {
      return length_;
    }
    /**
     * <code>int32 length = 1;</code>
     * @param value The length to set.
     * @return This builder for chaining.
     */
    public Builder setLength(int value) {

      length_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 length = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearLength() {
      bitField0_ = (bitField0_ & ~0x00000001);
      length_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.myz.wxapp.api.task.UserTask> tasks_ =
      java.util.Collections.emptyList();
    private void ensureTasksIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        tasks_ = new java.util.ArrayList<com.myz.wxapp.api.task.UserTask>(tasks_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.myz.wxapp.api.task.UserTask, com.myz.wxapp.api.task.UserTask.Builder, com.myz.wxapp.api.task.UserTaskOrBuilder> tasksBuilder_;

    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public java.util.List<com.myz.wxapp.api.task.UserTask> getTasksList() {
      if (tasksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tasks_);
      } else {
        return tasksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public int getTasksCount() {
      if (tasksBuilder_ == null) {
        return tasks_.size();
      } else {
        return tasksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public com.myz.wxapp.api.task.UserTask getTasks(int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);
      } else {
        return tasksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder setTasks(
        int index, com.myz.wxapp.api.task.UserTask value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.set(index, value);
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder setTasks(
        int index, com.myz.wxapp.api.task.UserTask.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.set(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder addTasks(com.myz.wxapp.api.task.UserTask value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder addTasks(
        int index, com.myz.wxapp.api.task.UserTask value) {
      if (tasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTasksIsMutable();
        tasks_.add(index, value);
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder addTasks(
        com.myz.wxapp.api.task.UserTask.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder addTasks(
        int index, com.myz.wxapp.api.task.UserTask.Builder builderForValue) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.add(index, builderForValue.build());
        onChanged();
      } else {
        tasksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder addAllTasks(
        java.lang.Iterable<? extends com.myz.wxapp.api.task.UserTask> values) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tasks_);
        onChanged();
      } else {
        tasksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder clearTasks() {
      if (tasksBuilder_ == null) {
        tasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        tasksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public Builder removeTasks(int index) {
      if (tasksBuilder_ == null) {
        ensureTasksIsMutable();
        tasks_.remove(index);
        onChanged();
      } else {
        tasksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public com.myz.wxapp.api.task.UserTask.Builder getTasksBuilder(
        int index) {
      return getTasksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public com.myz.wxapp.api.task.UserTaskOrBuilder getTasksOrBuilder(
        int index) {
      if (tasksBuilder_ == null) {
        return tasks_.get(index);  } else {
        return tasksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public java.util.List<? extends com.myz.wxapp.api.task.UserTaskOrBuilder> 
         getTasksOrBuilderList() {
      if (tasksBuilder_ != null) {
        return tasksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tasks_);
      }
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public com.myz.wxapp.api.task.UserTask.Builder addTasksBuilder() {
      return getTasksFieldBuilder().addBuilder(
          com.myz.wxapp.api.task.UserTask.getDefaultInstance());
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public com.myz.wxapp.api.task.UserTask.Builder addTasksBuilder(
        int index) {
      return getTasksFieldBuilder().addBuilder(
          index, com.myz.wxapp.api.task.UserTask.getDefaultInstance());
    }
    /**
     * <code>repeated .task.UserTask tasks = 2;</code>
     */
    public java.util.List<com.myz.wxapp.api.task.UserTask.Builder> 
         getTasksBuilderList() {
      return getTasksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.myz.wxapp.api.task.UserTask, com.myz.wxapp.api.task.UserTask.Builder, com.myz.wxapp.api.task.UserTaskOrBuilder> 
        getTasksFieldBuilder() {
      if (tasksBuilder_ == null) {
        tasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.myz.wxapp.api.task.UserTask, com.myz.wxapp.api.task.UserTask.Builder, com.myz.wxapp.api.task.UserTaskOrBuilder>(
                tasks_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        tasks_ = null;
      }
      return tasksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:task.QueryTaskResult)
  }

  // @@protoc_insertion_point(class_scope:task.QueryTaskResult)
  private static final com.myz.wxapp.api.task.QueryTaskResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.myz.wxapp.api.task.QueryTaskResult();
  }

  public static com.myz.wxapp.api.task.QueryTaskResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<QueryTaskResult>
      PARSER = new com.google.protobuf.AbstractParser<QueryTaskResult>() {
    @java.lang.Override
    public QueryTaskResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<QueryTaskResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<QueryTaskResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.myz.wxapp.api.task.QueryTaskResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

