// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: task.proto

package com.myz.wxapp.api.task;

public interface UserTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:task.UserTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>int64 userId = 2;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string description = 4;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 4;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>int32 status = 5;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>int32 taskType = 6;</code>
   * @return The taskType.
   */
  int getTaskType();

  /**
   * <code>int64 createTime = 7;</code>
   * @return The createTime.
   */
  long getCreateTime();

  /**
   * <code>.task.TaskExecution execution = 8;</code>
   * @return Whether the execution field is set.
   */
  boolean hasExecution();
  /**
   * <code>.task.TaskExecution execution = 8;</code>
   * @return The execution.
   */
  com.myz.wxapp.api.task.TaskExecution getExecution();
  /**
   * <code>.task.TaskExecution execution = 8;</code>
   */
  com.myz.wxapp.api.task.TaskExecutionOrBuilder getExecutionOrBuilder();
}
